services:
  postgres:
    restart: always
    image: postgres:latest
    container_name: postgres-Tomticket
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_tomticket
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./databaseBKP/tomticket.sql:/docker-entrypoint-initdb.d/tomticket.sql
  web:
    restart: always
    build: .
    container_name: get-Tomticket
    env_file:
      - .env
    ports:
      - 9443:9443
    volumes:
      - tomticket-data:/app
    depends_on:
      - postgres
volumes:
  postgres-data:
  tomticket-data: